version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5431:5432" # Порт PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: yet_another_kanban_board
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: